Show notice when syncing
slovensko-digital/govbox-pro pull request #310
Opened 2024-01-19 09:37 UTC by stage-rl

2024-01-19 09:39 UTC, stage-rl commented
![Screenshot_20240119_103828](https://github.com/slovensko-digital/govbox-pro/assets/10260098/258ff5dc-170f-46b5-809f-ca10a5f2f352)

2024-01-22 09:27 UTC, jsuchal commented on app/controllers/boxes_controller.rb
> +    redirect_back_or_to message_threads_path, notice: t("boxes.sync_all_running")
ked je to event `:box_sync_all_requested` tak aj tu by som cakal 
```suggestion
    redirect_back_or_to message_threads_path, notice: t("boxes.sync_all_requested")
```

2024-01-22 09:29 UTC, jsuchal commented on config/locales/sk.yml
> +    sync_all_running: "Synchronizácia správ bola spustená a prebieha na pozadí"
Prilis technicky slovnik na moj vkus a ked je tu taketo tlacitko, tak drzime rovnaky slovnik.

![image](https://github.com/slovensko-digital/govbox-pro/assets/26342/4c911809-a40b-4e42-adcb-798f9c2de006)


```suggestion
    sync_all_running: "Sťahovanie nových správ bolo spustené."
```

2024-01-22 09:30 UTC, jsuchal requested changes
Nejake male veci

2024-02-12 10:30 UTC, jsuchal approved these changes

2024-02-12 10:30 UTC, merged