Add thread_id to all message API endpoints
slovensko-digital/govbox-pro pull request #529
Opened 2024-12-18 22:06 UTC by czepiec

Is there any reason why the message `thread_id` is in the API `messages/sync` but not in `message/{id}` and `messages/search`?

This PR consistently adds the `thread_id` to `message/{id}` and `message/search`. But it's possible I'm missing something and it's meant to be without it.

It's not fully tested yet, so it's a draft.

2024-12-19 18:08 UTC, jsuchal commented
@czepiec this is good point, I don't see a reason why we should omit this.

2024-12-19 20:07 UTC, jsuchal approved these changes
Skusim tu dat approve kvoli testom

2024-12-20 07:24 UTC, luciajanikova requested changes
Po navrhnutych zmenach uz ok, testy zelene.

2024-12-20 07:24 UTC, luciajanikova commented on app/views/api/messages/show.json.jbuilder
> +json.thread_id message.message_thread_id
```suggestion
json.thread_id @message.message_thread_id
```

2024-12-20 07:24 UTC, luciajanikova commented on app/views/api/messages/search.json.jbuilder
> +json.thread_id message.message_thread_id
```suggestion
json.thread_id @message.message_thread_id
```

2024-12-20 07:53 UTC, jsuchal approved these changes

2024-12-20 07:55 UTC, luciajanikova approved these changes

2024-12-20 07:56 UTC, merged

2024-12-20 07:57 UTC, jsuchal commented
@czepiec diky!

2024-12-20 07:57 UTC, jsuchal commented
@luciajanikova dajme aj na prod